# Generated by Django 3.1.1 on 2022-08-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_private_key', '0002_auto_20220808_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.BinaryField(max_length=5000),
        ),
    ]
